# Generated by Django 5.1.3 on 2024-11-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
