# Generated by Django 5.1.3 on 2024-11-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_quantity4_cartorderitems_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tag',
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.vendor'),
        ),
    ]
